name: Run NSE Promoter News

on:
  #--------- comment bellow lines to disable the alert"------------------
  schedule:
    # Runs every day at 5:00 AM IST
    - cron: "30 23 * * *"   # Runs every day at 5:00 AM IST 
  workflow_dispatch:      # allow manual trigger
  #--------- comment above lines to disable the alert"------------------
jobs:
  run-news-script:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }} 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NSE promoter news script
        run: |
          python -m td.scripts.run_strategy --news promoter
